### ISSUE TITLE
Nameless Trinkets incompatible with Artifacts

### ISSUE THREAD

**Issue by RobertHDPotatoes** [Cozary/Issue-Tracker#5] opened 2021-11-18 03:40 UTC
Mod: Nameless Trinkets
Version: 1.16.5 1.0.0
Bug explanation: When you install Nameless Trinkets and Artifacts, Artifacts no longer show up in chests, chests that are supposed to have artifacts are empty (desert pyramid, mineshaft, etc) and it throws errors in the log file.
Bug image: 
Code (in case of a crash) (it can be an image or the code uploaded to a page such as https://hastebin.com): I also made this issue on the Artifacts github, you can find more details there. (https://github.com/ochotonida/artifacts/issues/117)

**Comment by ochotonida** [comment] 2021-11-18 10:48
This issue is caused by using the same loot pool name as Artifacts ('artifacts_inject') for injected loot pools. I'd suggest using a loot pool name that uses your mod id rather than Artifacts'.

**Comment by Cozary** [comment] 2021-11-19 19:28
The mod name was not determined until the last minute and I used several along the way, and that was not changed.
I actually just looked at it and that's fixed in the new version I was working on. Sorry for the inconvenience.

**Closed as completed by Cozary** 2021-11-19 19:28 UTC
Labels: compatibility
