### ISSUE TITLE
Wither Rose Bush has incorrect drop

### ISSUE THREAD

**Issue by niraqw** [Cozary/Issue-Tracker#3] opened 2021-09-18 05:01 UTC
Mod: Floral Enchantment
Version: 1.16.5-1.0.1
Bug explanation: The Wither Rose Bush drops Dandelions and Dandelion Vines when harvested. Additionally, using the pick block key on a Wither Rose Bush selects a Dandelion Bush.

**Comment by Cozary** [comment] 2021-09-18 18:33
Thanks for reporting it! The problem is now fixed and the versions fixed for 1.16.5 and 1.17.1 are being uploaded right now. ^^

**Closed as completed by Cozary** 2021-09-18 18:33 UTC
Labels: bug
